[Feat] Dark Mode
inplayer-org/inplayer-ui pull request #1069
Opened 2020-08-18 07:55 UTC by srdjanRakic

## OVERVIEW

_Add background theme options for dark mode._

## HOW CAN THIS BE MANUALLY TESTED?

_List steps to test this locally._

## CHECKLIST

_Be sure all items are_ ✅ _before submitting a PR for review._

- [ ] Verify the linters and tests pass: `yarn review`
- [ ] Verify you bumped the lib version according to [Semantic Versioning Standards](http://semver.org)
- [ ] Verify you updated the CHANGELOG
- [ ] Verify this branch is rebased with the latest master

2020-08-18 15:31 UTC, jase87 commented on src/paywall-previews/Preview1/Preview1.tsx
> +  InplayerPreviewBox1,
Why InplayerPreviewBox is renamed to InplayerPreviewBox1? Is there any particular reason to do that?

2020-08-19 07:27 UTC, ljubomirsk requested changes

2020-08-19 07:27 UTC, ljubomirsk commented on src/components/Accordion/AccordionPanel.tsx
> +  ${prop('imageWidth', '100%')};
Won't this just return the value of the `imageWidth` prop and not set it on any css property?

2020-08-19 07:30 UTC, srdjanRakic commented on src/components/Accordion/AccordionPanel.tsx
> +  ${prop('imageWidth', '100%')};
This is probably a copy/paste mistake, imageWidth prop does not exist in Accordion.

2020-08-19 07:39 UTC, ljubomirsk approved these changes

2020-08-19 08:16 UTC, merged