:feat: implement drawer component functionality and design
inplayer-org/inplayer-ui pull request #1292
Opened 2021-03-08 16:06 UTC by KristinaT

## OVERVIEW

Implemented a new drawer component

## WHERE SHOULD THE REVIEWER START?

`/src/components/Drawer.tsx`

## HOW CAN THIS BE MANUALLY TESTED?

_List steps to test this locally._

## ANY NEW DEPENDENCIES ADDED?

_List any new dependencies added._

- [ ] Does it work in IE >= 11?
- [ ] _Does it work in other browsers?_

## SCREENSHOTS (if applicable)

_Does your change affect the UI? If so, please add a screenshot._

## CHECKLIST

_Be sure all items are_ ✅ _before submitting a PR for review._

- [ ] Verify the linters and tests pass: `yarn review`
- [ ] Verify you bumped the lib version according to [Semantic Versioning Standards](http://semver.org)
- [ ] Verify you updated the CHANGELOG
- [ ] Verify this branch is rebased with the latest master

2021-03-10 11:54 UTC, jase87 requested changes

2021-03-10 11:54 UTC, jase87 commented on index.d.ts
> +  drawerIsOpen: boolean;
It is better to rename this prop to `isDrowerOpen`

2021-03-10 18:41 UTC, mirovladimitrovski commented on index.d.ts
> +  drawerIsOpen: boolean;
Or why not simply `isOpen`?

2021-09-23 12:28 UTC, mirovladimitrovski approved these changes

2021-09-23 12:31 UTC, Jasminna approved these changes

2021-09-23 12:31 UTC, merged