Refactored NavBar in  Typescript
inplayer-org/inplayer-ui pull request #678
Opened 2020-03-18 15:50 UTC by sandrananceva

## OVERVIEW

Refactored NavBar in Typescript

## WHERE SHOULD THE REVIEWER START?

`src/components/NavBar/index.tsx`

## CHECKLIST

_Be sure all items are_ ✅ _before submitting a PR for review._

- [ ] Verify the linters and tests pass: `yarn review`
- [ ] Verify you bumped the lib version according to [Semantic Versioning Standards](http://semver.org)
- [ ] Verify you updated the CHANGELOG
- [ ] Verify this branch is rebased with the latest master

2020-03-19 14:50 UTC, ljubomirsk requested changes

2020-03-19 14:50 UTC, ljubomirsk commented on src/components/NavBar/NavBar.tsx
> +// @flow
Remove this annotation everywhere

2020-03-19 14:50 UTC, ljubomirsk commented on src/components/NavBar/styled.tsx
> +export const NavbarLogo = styled.img<{ src?: any }>`
You shouldn't need to specify src as a prop since the `<img>` tag accepts that prop.

2020-03-20 14:12 UTC, sandrananceva commented on src/components/NavBar/NavBar.tsx
> +// @flow
Solved

2020-03-20 14:12 UTC, sandrananceva commented on src/components/NavBar/styled.tsx
> +export const NavbarLogo = styled.img<{ src?: any }>`
Solved

2020-03-25 11:11 UTC, closed without merging