Refactored Switch with Typescript
inplayer-org/inplayer-ui pull request #688
Opened 2020-03-19 15:54 UTC by sandrananceva

## OVERVIEW
Refactored Switch with Typescript

## WHERE SHOULD THE REVIEWER START?

 `src/elements/Switch/index.tsx`

## CHECKLIST

_Be sure all items are_ ✅ _before submitting a PR for review._

- [ ] Verify the linters and tests pass: `yarn review`
- [ ] Verify you bumped the lib version according to [Semantic Versioning Standards](http://semver.org)
- [ ] Verify you updated the CHANGELOG
- [ ] Verify this branch is rebased with the latest master

2020-03-19 17:40 UTC, mustran requested changes
Solve these problems and also don't forget to test the component into a separate project. It would be even better to include the `Usage.tsx` file here after testing, so we could use it later for testing the package as a whole  and also write docs from it. 
Lastly, delete the `switch.stories.js`

2020-03-19 17:40 UTC, mustran commented on src/elements/Switch/Switch.tsx
> +import Toggle from 'react-toggle';
`react-toggle` types are missing. You can add them by typing `yarn add @types/react-toggle`

2020-03-19 17:40 UTC, mustran commented on src/elements/Switch/Switch.tsx
> +    style?: Object;
use `CSSProperties` from styled-components instead of Object.

2020-03-19 17:40 UTC, mustran commented on src/elements/Switch/Switch.tsx
> +const MarginLeftLabel = styled(Label) <{ disabled?: boolean; }>`
prop `disabled` is not used in this styled component. It is redundant.

2020-03-19 17:40 UTC, mustran commented on src/elements/Switch/Switch.tsx
> +    onChange: (checked: boolean) => any;
You can use `void` instead of `any` here.

2020-03-19 17:40 UTC, mustran commented on src/elements/Switch/Switch.tsx
> +const Switch = ({ id, checked, label, disabled, onChange, className, style }: Props) => {
With ES6 you can set default values directly. So, it would be better to set the values directly here like this:

```tsx
const Switch = ({ id, checked, label, disabled = false, onChange, className = '', style = {} }: Props) 
```

2020-03-19 17:40 UTC, mustran commented on src/elements/Switch/Switch.tsx
> +Switch.defaultProps = {
If you set default values directly, then defining default props like this is redundant.

2020-03-19 17:40 UTC, mustran commented on src/elements/Switch/Switch.tsx
> +// @flow
Remove // @flow declaration.

2020-03-19 17:40 UTC, mustran commented on src/elements/Switch/Switch.tsx
> +/** @component */
Remove redundant comments.

2020-03-19 17:44 UTC, mustran requested changes

2020-03-19 17:44 UTC, mustran commented on src/elements/Switch/index.tsx
> +export default Switch;
Rename the file to `index.ts` since we are not using `JSX` here and export the file in one line:

```ts 
export { default as Switch } from './Switch';
```

2020-03-20 14:58 UTC, sandrananceva commented on src/elements/Switch/Switch.tsx
> +import Toggle from 'react-toggle';
It was already added.

2020-03-20 15:51 UTC, ljubomirsk commented on src/elements/Switch/Switch.tsx
> +const Switch = ({ id, checked, label, disabled, onChange, className, style }: Props) => {
If default props already exist let them stay. They are not anti-pattern and is fine having them.

2020-03-25 11:11 UTC, closed without merging