Complete TS rewrite
inplayer-org/inplayer-ui pull request #808
Opened 2020-04-28 13:10 UTC by srdjanRakic

2020-04-30 09:20 UTC, ljubomirsk requested changes

2020-04-30 09:20 UTC, ljubomirsk commented on src/elements/Button/Button.tsx
> +  icon?: ReactNode | null;
Same here with the icon type. Please check everywhere :smile:

2020-04-30 09:20 UTC, ljubomirsk commented on src/elements/Button/ButtonWrapper.ts
> +  buttonPrimary: ({ theme }: Record<string, any>) => `
I think there is no need for the type of the theme here

2020-04-30 09:20 UTC, ljubomirsk commented on src/elements/Card/Card.tsx
> +  style?: Record<string, any>;
Maybe this should be `CSSObject`? Check if it fits

2020-04-30 09:20 UTC, ljubomirsk commented on src/elements/Card/Card.tsx
> +const Card = ({ title, titleVariant = 'h1', style, children }: Props) => (
There isn't a type specified for children, either specify it in `Props` or use `React.FunctionComponent<Props>` type which has in itself children declaration.

2020-04-30 09:20 UTC, ljubomirsk commented on src/elements/DayPicker/DayPicker.tsx
> +  onDateChange: (date: Moment | null) => void;
Maybe think about returning `string` or `Date` type instead of Moment which makes a constraint to that library if you use this component.

2020-04-30 09:20 UTC, ljubomirsk commented on src/elements/Loader/Loader.tsx
> +  color = '#07AAE6',
Add this color to the colors if we don't already have it.

2020-04-30 09:20 UTC, ljubomirsk commented on src/elements/TextArea/Usate.tsx
> +const Usage = () => <TextArea defaultValue="Write Something ..." />;
The name of the file has a typo.

2020-04-30 09:38 UTC, mustran commented on src/components/NavBar/MenuItem.tsx
> +      <MenuItemIcon>{icon}</MenuItemIcon>
It is already fixed. Pull the latest version.

2020-04-30 09:51 UTC, mustran commented on src/elements/Accordion/AccordionPanel.tsx
> +      justify-content: space-beetween;
omg

2020-04-30 09:58 UTC, mustran commented on src/elements/Button/ButtonWrapper.ts
> +  buttonPrimary: ({ theme }: Record<string, any>) => `
It needs the type because it not used as `styled` .. It's just a variable, so it won't know about the `theme` type.

2020-05-04 10:17 UTC, mustran approved these changes

2020-05-04 10:26 UTC, ljubomirsk approved these changes

2020-05-04 10:30 UTC, merged